### ISSUE TITLE
sys.use_fifo_ui should not be applied as a universal tweak

### ISSUE THREAD

**Issue by Eamo5** [Magisk-Modules-Repo/MAGNETAR#1]
https://source.android.com/devices/tech/debug/jank_jitter#sys.use_fifo_ui
https://github.com/Magisk-Modules-Repo/MAGNETAR/blob/4bbe642a40151f09d80cb3036f04105fbd10bc2b/common/magnetar.prop#L89
Please research your props before adding them frivolously.

**Comment by celtare21** [comment]
> https://source.android.com/devices/tech/debug/jank_jitter#sys.use_fifo_ui
> https://github.com/Magisk-Modules-Repo/MAGNETAR/blob/4bbe642a40151f09d80cb3036f04105fbd10bc2b/common/magnetar.prop#L89
> 
> 
> Please research your props before adding them frivolously.

"Please research your props before adding them frivolously." lul 99% of this is total crap and the few ones that work are set up wrong

**Comment by Kyliekyler** [comment]
Fixed
